"""LLM-facing planning: task -> jobs, and empty backlog -> new tasks from the design doc."""
from __future__ import annotations

import re
import time
from pathlib import Path

from shared.jobs import Job, JobKind, make_job_id

from . import llm

MAX_JOBS_PER_TASK = 8


def _ctx(repo: Path, *rel: str) -> str:
    parts = []
    for r in rel:
        p = repo / r
        if p.exists():
            parts.append(f"## {r}\n" + p.read_text())
    return "\n\n".join(parts)


def plan_jobs(repo: Path, task_path: Path, escalate: bool = False) -> list[Job]:
    system = llm.load_role(repo, "orchestrator")
    user = "\n\n".join([
        "## Task\n" + task_path.read_text(),
        _ctx(repo, "style/style-bible.md", "docs/08-job-schema.md", "docs/10-game-design.md"),
        "Existing approved assets:\n" + "\n".join(str(p.relative_to(repo)) for p in (repo / "assets" / "approved").rglob("*") if p.is_file())[:4000],
        "Respond with JSON: {\"jobs\": [ ... ]}. Each job: kind (stub|image|music|sfx|code), "
        "role, spec (object), output_dir (under assets/incoming/<task-id>-<slug>/ for assets, or "
        "\"game\" for code), slug (short). For code jobs, spec.goal is the instruction to the coder "
        f"and spec.acceptance is a checklist. At most {MAX_JOBS_PER_TASK} jobs. Prefer few, small jobs. "
        "Optional keys: \"decisions\": [strings] for any choice you made on the owner's behalf "
        "(logged automatically), and \"style_bible\": full replacement text for style/style-bible.md "
        "when the task asks you to fill it in.",
    ])
    task_id = task_path.stem.split("-")[0]
    data = llm.chat_json(system, user, model=llm.escalation_model() if escalate else None)
    raw = data["jobs"] if isinstance(data, dict) else data
    if isinstance(data, dict):
        record_side_effects(repo, task_path, data)
    jobs: list[Job] = []
    for rj in raw[:MAX_JOBS_PER_TASK]:
        slug = re.sub(r"[^a-z0-9]+", "-", str(rj.pop("slug", "job")).lower()).strip("-")[:30] or "job"
        for k in ("id", "task_id", "created_at", "attempt"):
            rj.pop(k, None)
        rj.setdefault("output_dir", f"assets/incoming/{task_id}-{slug}")
        jobs.append(Job(id=make_job_id(task_id, slug), task_id=task_id, **rj))
    return jobs


def next_task_id(repo: Path) -> str:
    ids = [0]
    for d in ("backlog", "in-progress", "done", "deferred"):
        for p in (repo / "tasks" / d).glob("*.md"):
            m = re.match(r"(\d+)-", p.name)
            if m:
                ids.append(int(m.group(1)))
    return f"{max(ids) + 1:03d}"


def generate_backlog(repo: Path, count: int = 5) -> list[Path]:
    """Ask the orchestrator model for the next few tasks based on the design doc and what is done."""
    system = llm.load_role(repo, "orchestrator")
    done = "\n".join(p.name for p in sorted((repo / "tasks" / "done").glob("*.md")))
    deferred = "\n".join(p.name for p in sorted((repo / "tasks" / "deferred").glob("*.md")))
    user = "\n\n".join([
        _ctx(repo, "docs/10-game-design.md", "docs/01-vision.md", "style/style-bible.md", "tasks/README.md"),
        "## Done tasks\n" + (done or "(none)"),
        "## Deferred tasks (do not repeat these)\n" + (deferred or "(none)"),
        f"The backlog is empty. Propose the next {count} tasks that move the prototype forward, "
        "smallest first, each doable by one or two roles in under an hour of worker time. "
        "Respond with JSON: {\"tasks\": [{\"title\": ..., \"priority\": 1-9, \"roles\": [...], "
        "\"goal\": ..., \"acceptance\": [...], \"notes\": ...}]}",
    ])
    data = llm.chat_json(system, user)
    created = []
    for t in data.get("tasks", [])[:count]:
        tid = next_task_id(repo)
        slug = re.sub(r"[^a-z0-9]+", "-", t["title"].lower()).strip("-")[:40]
        body = (f"# {tid} {t['title']}\npriority: {t.get('priority', 5)}\n"
                f"roles: {', '.join(t.get('roles', []))}\n\n## Goal\n{t.get('goal', '')}\n\n"
                "## Acceptance\n" + "\n".join(f"- {a}" for a in t.get("acceptance", [])) +
                f"\n\n## Notes\n{t.get('notes', '')}\n\n_generated by orchestrator {time.strftime('%Y-%m-%d %H:%M')}_\n")
        p = repo / "tasks" / "backlog" / f"{tid}-{slug}.md"
        p.write_text(body)
        created.append(p)
    return created


def record_side_effects(repo: Path, task_path: Path, data: dict) -> None:
    """Auto decisions and style-bible rewrites that came back with a plan."""
    day = time.strftime("%Y-%m-%d")
    decisions = [str(d) for d in data.get("decisions") or []][:10]
    if decisions:
        with (repo / "docs" / "decisions.md").open("a") as f:
            for d in decisions:
                f.write(f"| {day} | (auto) {d.replace('|', '/')} | orchestrator, task {task_path.stem} |\n")
        with task_path.open("a") as f:
            f.write("\n- auto decisions: " + "; ".join(decisions))
    sb = data.get("style_bible")
    if isinstance(sb, str) and len(sb) > 200 and "## Visual style" in sb:
        (repo / "style" / "style-bible.md").write_text(sb)
        with task_path.open("a") as f:
            f.write("\n- style bible rewritten by orchestrator")
